apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodejs-service
  labels:
    app: hello-world-nodejs
spec:
  type: LoadBalancer
  selector:
    app: hello-world-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3007
